package Vistas;

import Modelo.Productos222.Productos;
import clases.Planilla;
import clases.Pluses;
import clases.PlusesColab;
import Modelo.Proveedores.Proveedor;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Crisp
 */
public class PaniSys extends javax.swing.JFrame {

    //Creación de todos los ArrayList para luego ser llamados.
    ArrayList<Productos> listaC = new ArrayList();
    ArrayList<Pluses> listaPluses = new ArrayList();
    ArrayList<Proveedor> listaPuestos = new ArrayList();
    ArrayList<PlusesColab> listaPColab = new ArrayList();
    ArrayList<Planilla> listaPlanilla = new ArrayList();

    /**
     * Creates new form PaniSys
     */
    public PaniSys() {
        initComponents();
        setLocationRelativeTo(null);

        // Crear menú
        JMenuBar menuBar = new JMenuBar();
        JMenu menuJuego = new JMenu("Gestión de Colaboradores");
        JMenuItem itemIniciar = new JMenuItem("Gestión de Pluses");
        JMenuItem itemAbortar = new JMenuItem("Gestión de Puestos");
        JMenuItem itemUltimoGanador = new JMenuItem("Asignar Pluses");
        JMenuItem itemAcercaDe = new JMenuItem("Planillas");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGestionPuestos = new javax.swing.JButton();
        btnAsignarPls = new javax.swing.JButton();
        btnGestionColab = new javax.swing.JButton();
        btnPlanillas = new javax.swing.JButton();
        btnGestionPluses = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        mnuMenuBar = new javax.swing.JMenuBar();
        mnuMenu = new javax.swing.JMenu();
        mnuItemGesColab = new javax.swing.JMenuItem();
        mnuItemGesPlus = new javax.swing.JMenuItem();
        mnuItemGesPuestos = new javax.swing.JMenuItem();
        mnuAsigPlus = new javax.swing.JMenuItem();
        mnuPlanilla = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Gestión de Plantillas ");
        setIconImage(getIconImage());

        btnGestionPuestos.setText("Gestión de Puestos");
        btnGestionPuestos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnGestionPuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionPuestosActionPerformed(evt);
            }
        });

        btnAsignarPls.setText("Asignar Pluses");
        btnAsignarPls.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnAsignarPls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarPlsActionPerformed(evt);
            }
        });

        btnGestionColab.setText("Gestión de Colaboradores");
        btnGestionColab.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnGestionColab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionColabActionPerformed(evt);
            }
        });

        btnPlanillas.setText("Planillas");
        btnPlanillas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnPlanillas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlanillasActionPerformed(evt);
            }
        });

        btnGestionPluses.setText("Gestión de Pluses");
        btnGestionPluses.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnGestionPluses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionPlusesActionPerformed(evt);
            }
        });

        jButton1.setText("Clientes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        mnuMenu.setText("Menú");

        mnuItemGesColab.setText("Gestión de Colaboradores");
        mnuItemGesColab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemGesColabActionPerformed(evt);
            }
        });
        mnuMenu.add(mnuItemGesColab);

        mnuItemGesPlus.setText("Gestión de Pluses");
        mnuItemGesPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemGesPlusActionPerformed(evt);
            }
        });
        mnuMenu.add(mnuItemGesPlus);

        mnuItemGesPuestos.setText("Gestión de Puestos");
        mnuItemGesPuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemGesPuestosActionPerformed(evt);
            }
        });
        mnuMenu.add(mnuItemGesPuestos);

        mnuAsigPlus.setText("Asignar Pluses");
        mnuAsigPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAsigPlusActionPerformed(evt);
            }
        });
        mnuMenu.add(mnuAsigPlus);

        mnuPlanilla.setText("Planillas");
        mnuPlanilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPlanillaActionPerformed(evt);
            }
        });
        mnuMenu.add(mnuPlanilla);

        mnuMenuBar.add(mnuMenu);

        setJMenuBar(mnuMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnAsignarPls, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnGestionPuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnGestionColab, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPlanillas, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnGestionPluses, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGestionColab, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestionPluses, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGestionPuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlanillas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAsignarPls, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionColabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionColabActionPerformed
        FrmProductos winColaborador = new FrmProductos(this, false, listaC, listaPuestos);
        winColaborador.setVisible(true);
        //Lo que hace es que los datos del JDialog los devuelve 
        this.listaC = winColaborador.lista;
    }//GEN-LAST:event_btnGestionColabActionPerformed

    private void btnGestionPlusesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionPlusesActionPerformed
        PlusesView winPluses = new PlusesView(this, false, listaPluses);
        winPluses.setVisible(true);
        //Lo que hace es que los datos del JDialog los devuelve 
        this.listaPluses = winPluses.lista;
    }//GEN-LAST:event_btnGestionPlusesActionPerformed

    private void btnGestionPuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionPuestosActionPerformed
        FrmProveedores winPuestos = new FrmProveedores(this, false, listaPuestos);
        winPuestos.setVisible(true);
        //Lo que hace es que los datos del JDialog los devuelve 
        this.listaPuestos = winPuestos.lista;
    }//GEN-LAST:event_btnGestionPuestosActionPerformed

    private void btnAsignarPlsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarPlsActionPerformed
        PlusesColabView winPlusesColab = new PlusesColabView(this, false, listaPColab, listaPluses, listaC);
        winPlusesColab.setVisible(true);
        //Lo que hace es que los datos del JDialog los devuelve 
        this.listaPColab = winPlusesColab.listaPColab;
    }//GEN-LAST:event_btnAsignarPlsActionPerformed

    private void btnPlanillasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlanillasActionPerformed
        PlanillaView winPlanilla = new PlanillaView(this, false, listaPlanilla, listaPuestos, listaPColab, listaPluses, listaC);
        winPlanilla.setVisible(true);
        //Lo que hace es que los datos del JDialog los devuelve 
        this.listaPlanilla = winPlanilla.listaPlanilla;
    }//GEN-LAST:event_btnPlanillasActionPerformed

    private void mnuItemGesColabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemGesColabActionPerformed
        FrmProductos winColaborador = new FrmProductos(this, false, listaC, listaPuestos);
        winColaborador.setVisible(true);
        //Lo que hace es que los datos del JDialog los devuelve 
        this.listaC = winColaborador.lista;
    }//GEN-LAST:event_mnuItemGesColabActionPerformed

    private void mnuAsigPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAsigPlusActionPerformed
        PlusesColabView winPlusesColab = new PlusesColabView(this, false, listaPColab, listaPluses, listaC);
        winPlusesColab.setVisible(true);
        //Lo que hace es que los datos del JDialog los devuelve 
        this.listaPColab = winPlusesColab.listaPColab;
    }//GEN-LAST:event_mnuAsigPlusActionPerformed

    private void mnuItemGesPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemGesPlusActionPerformed
        PlusesView winPluses = new PlusesView(this, false, listaPluses);
        winPluses.setVisible(true);
        //Lo que hace es que los datos del JDialog los devuelve 
        this.listaPluses = winPluses.lista;
    }//GEN-LAST:event_mnuItemGesPlusActionPerformed

    private void mnuItemGesPuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemGesPuestosActionPerformed
        FrmProveedores winPuestos = new FrmProveedores(this, false, listaPuestos);
        winPuestos.setVisible(true);
        //Lo que hace es que los datos del JDialog los devuelve 
        this.listaPuestos = winPuestos.lista;
    }//GEN-LAST:event_mnuItemGesPuestosActionPerformed

    private void mnuPlanillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPlanillaActionPerformed
        PlanillaView winPlanilla = new PlanillaView(this, false, listaPlanilla, listaPuestos, listaPColab, listaPluses, listaC);
        winPlanilla.setVisible(true);
        //Lo que hace es que los datos del JDialog los devuelve 
        this.listaPlanilla = winPlanilla.listaPlanilla;
    }//GEN-LAST:event_mnuPlanillaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FrmCliente view = new FrmCliente(this,true);
        view.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource(
                        "img/recurso.png"));
        return retValue;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaniSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaniSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaniSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaniSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaniSys().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignarPls;
    private javax.swing.JButton btnGestionColab;
    private javax.swing.JButton btnGestionPluses;
    private javax.swing.JButton btnGestionPuestos;
    private javax.swing.JButton btnPlanillas;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuItem mnuAsigPlus;
    private javax.swing.JMenuItem mnuItemGesColab;
    private javax.swing.JMenuItem mnuItemGesPlus;
    private javax.swing.JMenuItem mnuItemGesPuestos;
    private javax.swing.JMenu mnuMenu;
    private javax.swing.JMenuBar mnuMenuBar;
    private javax.swing.JMenuItem mnuPlanilla;
    // End of variables declaration//GEN-END:variables
}
