package Vistas;

import Modelo.Productos.Productos;
import clases.Pluses;
import clases.PlusesColab;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Christian y Reyman 
 */
public class PlusesColabView extends javax.swing.JDialog {

    //Array Lits y objetos de clases determinadas
    PlusesColab pluses;
    ArrayList<PlusesColab> listaPColab;
    ArrayList<Pluses> listaPluses;
    ArrayList<Productos> listaC;
    DefaultTableModel model;

    /**
     *
     *
     * @param parent
     * @param modal
     * @param listaPColab lista de Pluses Asinar a Colaboradores
     * @param listaPluses lista de pluses
     * @param listaC de colaboradores
     */
    public PlusesColabView(java.awt.Frame parent, boolean modal, ArrayList<PlusesColab> listaPColab,
            ArrayList<Pluses> listaPluses, ArrayList<Productos> listaC) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.listaC = listaC;
        this.listaPluses = listaPluses;
        this.listaPColab = listaPColab;
    }

    /**
     *
     * @param parent
     * @param modal
     */
    public PlusesColabView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatos = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        txtCedulaT = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        btnBuscarCed = new javax.swing.JButton();
        cmbNombrePlus = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPlusesColab = new javax.swing.JTable();
        pnlBotones = new javax.swing.JPanel();
        btnInsertar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        lblCant = new javax.swing.JLabel();
        txtCant = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Asignar Pluses ");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        pnlDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos del Plus", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        lblId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblId.setText("Cédula del trabajador");

        txtCedulaT.setEditable(false);
        txtCedulaT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombre.setText("Título del Plus:");

        btnBuscarCed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btnBuscarCed.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscarCed.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBuscarCed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCedulaT, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                    .addComponent(cmbNombrePlus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarCed, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblId))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCedulaT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarCed, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(cmbNombrePlus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        tblPlusesColab.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblPlusesColab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblPlusesColab.getTableHeader().setReorderingAllowed(false);
        tblPlusesColab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblPlusesColabMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblPlusesColab);

        pnlBotones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/insert.png"))); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clean.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnEliminar)
                .addGap(38, 38, 38)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        lblBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        lblBuscar.setText("Buscar: ");

        txtBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        lblCant.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCant.setText("Cantidad de registros:");

        txtCant.setEditable(false);
        txtCant.setBackground(new java.awt.Color(204, 204, 204));
        txtCant.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblCant)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(455, 455, 455))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblBuscar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(15, 15, 15))))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCant)
                    .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 /**
     * Botón para limpiar los campos de escritura o asignación.
     *
     * @param evt ActionPerformed
     */
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtCedulaT.setText("");
        txtCedulaT.requestFocus();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * Botón para insertar todos los datos al JTable de PlusesColaborador.
     *
     * @param evt ActionPerformed
     */
    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        PlusesColab plusesColab = new PlusesColab();

        try {
            // Obtener y limpiar el texto del campo de cédula
            String textValue = txtCedulaT.getText().trim();

            // Verificar si el campo de cédula no está vacío
            if (!textValue.isEmpty()) {
                int cedula = Integer.parseInt(textValue); // Convertir a entero

                // Verificar si se seleccionó un ítem en el combo box
                if (cmbNombrePlus.getSelectedIndex() != -1) {
                    String nombrePlus = cmbNombrePlus.getItemAt(cmbNombrePlus.getSelectedIndex());

                    // Verificar si ya existe el nombre y la cédula en la base de datos
                    if (existeNombre(nombrePlus) && existeCedula(cedula)) {
                        JOptionPane.showMessageDialog(this, "Este Plus ya fue asignado al colaborador seleccionado.");
                    } else {
                        // Asignar los valores al objeto plusesColab
                        plusesColab.setCedula(cedula);
                        plusesColab.setNombresPluses(nombrePlus);

                        // Intentar agregar el plus al colaborador
                        if (listaPColab.add(plusesColab)) {
                            JOptionPane.showMessageDialog(this, "Plus asignado");
                            mostrarTabla();
                            btnLimpiarActionPerformed(null); // Limpiar el formulario
                        } else {
                            JOptionPane.showMessageDialog(this, "Error al insertar");
                        }
                    }
                } else {
                    // Mostrar un mensaje si no se seleccionó ningún ítem en el combo box
                    JOptionPane.showMessageDialog(this, "Debe seleccionar un plus del combo box.", "Selección inválida", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                // Mostrar un mensaje si el campo de cédula está vacío
                JOptionPane.showMessageDialog(this, "El campo de cédula no puede estar vacío. Por favor, ingrese un valor.");
            }

        } catch (NumberFormatException ex) {
            // Manejar la excepción si el valor de la cédula no es un número válido
            JOptionPane.showMessageDialog(this, "El valor ingresado en la cédula no es un número válido. Por favor, verifique e intente nuevamente.", "Error de formato", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInsertarActionPerformed
    /**
     * Evento en el cual busca los registros que hay en el JTable.
     *
     * @param evt
     */

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        String titulos[] = {"CédulaTrabajador", "PlusesAgregados"};
        model = new DefaultTableModel(null, titulos);

        for (int i = 0; i < listaPColab.size(); i++) {
            pluses = listaPColab.get(i);
            if (String.valueOf(pluses.getCedula()).toLowerCase().contains(txtCedulaT.getText().toLowerCase())) {
                Object nuevaFila[] = {pluses.getCedula(), pluses.getNombresPluses()};
                model.addRow(nuevaFila);
            }
        }
        tblPlusesColab.setModel(model);

        txtCant.setText(String.valueOf(model.getRowCount()));
    }//GEN-LAST:event_txtBuscarKeyReleased

    /**
     * Evento que se atica cuando se presiona los registros del JTable y se
     * muesrran en los cuadros de texto.
     *
     * @param evt
     */
    private void tblPlusesColabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPlusesColabMousePressed
        if (evt.getClickCount() == 1) {
            txtCedulaT.setText(String.valueOf(tblPlusesColab.getValueAt(tblPlusesColab.getSelectedRow(), 0)));
            cmbNombrePlus.setName(String.valueOf(tblPlusesColab.getValueAt(tblPlusesColab.getSelectedRow(), 1)));
        }
    }//GEN-LAST:event_tblPlusesColabMousePressed
    /**
     * Botón para eliminar un registro seleccionado.
     *
     * @param evt
     */
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (tblPlusesColab.getSelectedRowCount() == 1) {
            int resp = JOptionPane.showConfirmDialog(this, "¿Desea borrar el resgitro?");
            if (resp == 0) {  //El usuario quiere eliminar, Respuesta si
                int fila = tblPlusesColab.getSelectedRow();
                if (listaPColab.remove(listaPColab.get(fila))) {
                    mostrarTabla();
                } else {
                    JOptionPane.showMessageDialog(this, "Error de borrado");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Se debe seleccionar 1 registro");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed
    /**
     * Botón para editar un regsitro seleccionado.
     *
     * @param evt
     */
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (tblPlusesColab.getSelectedRowCount() == 1) {

            int fila = tblPlusesColab.getSelectedRow();
            pluses = new PlusesColab();

            if (cmbNombrePlus.getSelectedItem() != null) {

                pluses.setCedula(Integer.parseInt(
                tblPlusesColab.getValueAt(fila, 0).toString()));
                pluses.setNombresPluses(cmbNombrePlus.getSelectedItem().toString()); 

                if (listaPColab.set(fila, pluses) != null) {
                    JOptionPane.showMessageDialog(
                            this, "Plus editado");
                    mostrarTabla();
                    btnLimpiarActionPerformed(null);
                } else {
                    JOptionPane.showMessageDialog(
                            this, "Error al editar");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un nombre de plus");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Se debe seleccionar 1 registro para editar");
        }
    }//GEN-LAST:event_btnEditarActionPerformed
    /**
     * Muestra el titulo de los pluse agregados en la clases pluses, para así
     * sleeccionar por medio de un combo box
     *
     * @param evt
     */
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if (cmbNombrePlus.getItemCount() <= 0) {
            for (Pluses p : listaPluses) {
                cmbNombrePlus.addItem(p.getTitulo());
            }
        }
        mostrarTabla();
    }//GEN-LAST:event_formWindowActivated
    /**
     * mostrar un table con los datos de los colaboradores y por default se
     * seleccioné su cédula.
     *
     * @param evt
     */
    private void btnBuscarCedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCedActionPerformed
        if (listaC.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Aún no hay colaboradores registrados", "Lista vacía", JOptionPane.INFORMATION_MESSAGE);
        } else {
            ColaboradorBuscaView winBuscarColab = new ColaboradorBuscaView(null, true, listaC);
            winBuscarColab.setVisible(true);
            txtCedulaT.setText(winBuscarColab.cedula);
        }
    }//GEN-LAST:event_btnBuscarCedActionPerformed
    /**
     * Muestra los datos y títulos en el JTable
     */
    public void mostrarTabla() {
        String titulos[] = {"CédulaTrabajador", "PlusesAgregados"};
        model = new DefaultTableModel(null, titulos);
        //No se usó el foreach porque el índice lo estamos necesitando 
        for (int i = 0; i < listaPColab.size(); i++) {
            pluses = listaPColab.get(i);
            Object nuevaFila[] = {pluses.getCedula(), pluses.getNombresPluses()};
            model.addRow(nuevaFila);
        }
        tblPlusesColab.setModel(model);

        txtCant.setText(String.valueOf(model.getRowCount()));
    }

    /**
     * Verifica si un plus con el nombre dado ya existe en la lista de
     * PlusesColab.
     *
     * @param nombresPluses El nombre del plus a verificar.
     * @return true si el nombre del plus ya existe en la lista, false en caso
     * contrario.
     */
    public boolean existeNombre(String nombresPluses) {
        for (int i = 0; i < listaPColab.size(); i++) {
            pluses = listaPColab.get(i);
            if (pluses.getNombresPluses().equals(nombresPluses)) {
                return true;
            }
        }
        return false;
    }

    /**
     * Verifica si un empleado con la cédula dada ya existe en la lista de
     * PlusesColab.
     *
     * @param cedulaEmpleado La cédula del empleado a verificar.
     * @return true si la cédula del empleado ya existe en la lista, false en
     * caso contrario.
     */
    public boolean existeCedula(int cedulaEmpleado) {
        for (int i = 0; i < listaPColab.size(); i++) {
            pluses = listaPColab.get(i);
            if (pluses.getCedula() == cedulaEmpleado) {
                return true;
            }
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlusesColabView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlusesColabView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlusesColabView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlusesColabView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PlusesColabView dialog = new PlusesColabView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCed;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cmbNombrePlus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblCant;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JTable tblPlusesColab;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCant;
    private javax.swing.JTextField txtCedulaT;
    // End of variables declaration//GEN-END:variables
}
